CONFIG_NICE_OLED_ON=y
CONFIG_NICE_OLED_WIDGET_STATUS=y
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n
CONFIG_I2C=y
CONFIG_SSD1306=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=y
